# @Author: Daniel Fernandes
# @Date:   2025-04-08 15:47:47
# @Last Modified by:   Daniel Fernandes
# @Last Modified time: 2025-04-08 15:55:34
stages:
  train:
    cmd: python src/main.py
    deps:
    - data
    - src/main.py
plots:
- dvclive/plots/metrics:
    x: step
